FROM golang:latest as builder

COPY . .
WORKDIR go/src/github.com/glefloch/zbootcamp

RUN CGO_ENABLED=0 GOOS=linux go build -v -o /zbootcamp

FROM scratch
COPY --from=builder /zbootcamp /zbootcamp

ENTRYPOINT ["/zbootcamp"]
